/**
 * 宠头头 · 宠物搭子交友 Mock（对齐交付文档 MVP）
 */

const BASE = '/assets/mock';

const REAL = {
  avatar: `${BASE}/real_avatar.jpg`,
  tallDog: `${BASE}/real_tall_dog.jpg`,
  cat: `${BASE}/real_cat.jpg`,
  pup: `${BASE}/real_pup.jpg`,
  hero: `${BASE}/real_hero.jpg`,
  svc1: `${BASE}/real_svc1.jpg`,
  svc2: `${BASE}/real_svc2.jpg`,
};

const MOCK_PET = {
  name: '豆豆',
  breed: '柴犬',
  breedName: '柴犬',
  species: 2,
  age: '2岁',
  gender: 1,
  isSterilized: true,
  verified: true,
  personality: '活泼外向',
  socialTags: ['爱遛狗', '友好', '已绝育'],
  avatar: REAL.avatar,
  avatarUrl: REAL.avatar,
  cover: REAL.hero,
};

const MOCK_HOME = {
  city: '北京',
  banners: [
    { id: 'b1', title: '周末携宠露营季', cover: REAL.hero, type: 'official' },
    { id: 'b2', title: '宠物友好咖啡馆地图上线', cover: REAL.cat, type: 'platform' },
    { id: 'b3', title: '同城遛狗搭子招募中', cover: REAL.pup, type: 'event' },
  ],
  /** 首页 bento 宫格（参照布丁 Pudding 风格） */
  featureTiles: {
    buddy: {
      id: 'buddy',
      name: '宠友搭子',
      subtitle: '用「陪伴」融化它们的孤独',
      deco: '🐕',
      theme: 'blue',
      layout: 'large',
      path: '/pages/buddy/buddy',
      thumbs: [REAL.avatar, REAL.cat, REAL.pup],
    },
    event: {
      id: 'event',
      name: '发起活动',
      subtitle: '同城宠友一起玩',
      deco: '🎾',
      theme: 'yellow',
      layout: 'wide',
      path: '/pages/event-publish/event-publish',
    },
    map: {
      id: 'map',
      name: '友好地图',
      subtitle: '携宠友好点位',
      deco: '🌳',
      theme: 'green',
      layout: 'wide-half',
      path: '/pages/local/local?tab=map',
    },
    rescue: {
      id: 'rescue',
      name: '寻宠领养',
      subtitle: '走失寻回 · 爱心领养',
      deco: '🐕‍🦺',
      theme: 'pink',
      layout: 'small',
      path: '/pages/pet-rescue/pet-rescue',
    },
    service: {
      id: 'service',
      name: '本地服务',
      subtitle: '互助 · 洗护 · 医院',
      deco: '✂️',
      theme: 'cyan',
      layout: 'wide-half',
      path: '/pages/local/local?tab=service',
    },
    cert: {
      id: 'cert',
      name: '电子宠证',
      subtitle: '数字宠物 · 档案',
      deco: '🪪',
      theme: 'gold',
      layout: 'small',
      path: '/pages/pet-cert/pet-cert',
    },
  },
  grid: [],
};

const BUDDY_TYPES = ['遛狗搭子', '撸猫搭子', '携宠旅行搭子', '露营搭子', '宠物下午茶', '异宠交流', '宠物相亲&借配'];

const MOCK_BUDDY = [
  {
    id: 'bd1',
    userName: '芒果爸',
    avatar: REAL.pup,
    distance: '0.8km',
    petName: '芒果',
    breed: '金毛',
    age: '3岁',
    verified: true,
    personality: '温柔耐心',
    buddyType: '遛狗搭子',
    tags: ['大型犬', '已绝育'],
    expectTime: '周末上午',
    expectPlace: '朝阳公园',
    desc: '想找同体型狗狗一起慢跑，芒果性格很好，不扑人。',
    creditTags: ['守约', '宠物温顺'],
    zone: 'normal',
    mediaList: [
      { type: 'image', url: REAL.pup },
      { type: 'image', url: REAL.hero },
      { type: 'video', url: REAL.pup, poster: REAL.pup, duration: 12 },
    ],
    cover: REAL.pup,
  },
  {
    id: 'bd2',
    userName: '布偶姐姐',
    avatar: REAL.cat,
    distance: '1.2km',
    petName: '糯米',
    breed: '布偶猫',
    age: '1岁',
    verified: true,
    personality: '慢热粘人',
    buddyType: '宠物下午茶',
    tags: ['室内猫', '已疫苗'],
    expectTime: '周日下午',
    expectPlace: '三里屯猫咖',
    desc: '希望找慢热猫咪家长，一起适应社交环境。',
    creditTags: ['守约'],
    zone: 'normal',
    mediaList: [
      { type: 'image', url: REAL.cat },
      { type: 'image', url: REAL.avatar },
    ],
    cover: REAL.cat,
  },
  {
    id: 'bd3',
    userName: '柯基小队',
    avatar: REAL.avatar,
    distance: '2.1km',
    petName: '短腿',
    breed: '柯基',
    age: '2岁',
    verified: false,
    personality: '话痨社牛',
    buddyType: '露营搭子',
    tags: ['小型犬', '爱拍照'],
    expectTime: '下月初',
    expectPlace: '怀柔营地',
    desc: '计划携宠露营，找2-3个小型犬家庭同行。',
    creditTags: ['守约', '文明养宠'],
    zone: 'normal',
    mediaList: [
      { type: 'image', url: REAL.hero },
      { type: 'video', url: REAL.tallDog, poster: REAL.tallDog, duration: 18 },
      { type: 'image', url: REAL.pup },
      { type: 'image', url: REAL.avatar },
    ],
    cover: REAL.hero,
  },
  {
    id: 'bd4',
    userName: '柴犬研究社',
    avatar: REAL.avatar,
    distance: '3.0km',
    petName: '小柴',
    breed: '柴犬',
    age: '2岁',
    verified: true,
    personality: '活泼',
    buddyType: '宠物相亲&借配',
    tags: ['已疫苗', '血统证书'],
    expectTime: '可协商',
    expectPlace: '宠物医院见面',
    desc: '寻找健康同龄柴犬借配，需出示疫苗与体检记录。',
    creditTags: [],
    zone: 'match',
    mediaList: [
      { type: 'image', url: REAL.tallDog },
      { type: 'video', url: REAL.avatar, poster: REAL.avatar, duration: 8 },
    ],
    cover: REAL.tallDog,
  },
];

const MOCK_SOCIAL = {
  innerTabs: [
    { id: 'all', name: '全部动态' },
    { id: 'featured', name: '社区精选' },
    { id: 'circle', name: '圈子分类' },
    { id: 'topic', name: '话题' },
    { id: 'qa', name: '问答求助' },
  ],
  circles: [
    { id: 'c1', name: '柯基圈', icon: '🐕', members: 1280, cover: REAL.tallDog },
    { id: 'c2', name: '布偶猫圈', icon: '🐱', members: 960, cover: REAL.cat },
    { id: 'c3', name: '异宠圈', icon: '🦔', members: 420, cover: REAL.pup },
    { id: 'c4', name: '携宠旅行圈', icon: '🐕‍🦺', members: 680, cover: REAL.hero },
  ],
  topics: [
    { id: 't1', name: '#携宠露营', posts: 128, hot: true },
    { id: 't2', name: '#猫咪喂养', posts: 86 },
    { id: 't3', name: '#避雷宠物店', posts: 204, hot: true },
    { id: 't4', name: '#第一次见朋友', posts: 67 },
  ],
  qaList: [
    { id: 'q1', userName: '新手铲屎官', title: '两个月幼犬可以社交吗？', answers: 8, best: true },
    { id: 'q2', userName: '猫奴小白', title: '猫咪出门应激怎么办？', answers: 12, best: false },
  ],
  posts: [
    {
      id: 'p1',
      userName: '小橘妈',
      petName: '橘子',
      avatar: REAL.cat,
      circle: '布偶猫圈',
      location: '朝阳区',
      time: '10 分钟前',
      zone: 'cat',
      topic: '#携宠露营',
      content: '周末有没有朝阳附近一起遛猫社交的？橘子最近交友欲超强 🐾',
      likes: 24,
      comments: 8,
      liked: false,
      shares: 3,
      image: REAL.cat,
    },
    {
      id: 'p2',
      userName: '阿柴爸爸',
      petName: '团团',
      avatar: REAL.avatar,
      circle: '柯基圈',
      location: '海淀区',
      time: '1 小时前',
      zone: 'dog',
      topic: '#第一次见朋友',
      content: '团团第一次见朋友，尾巴摇成螺旋桨了～',
      likes: 56,
      comments: 13,
      liked: true,
      image: REAL.tallDog,
      essence: true,
      shares: 12,
    },
    {
      id: 'p-lost1',
      userName: '豆豆爸',
      petName: '豆豆',
      avatar: REAL.avatar,
      circle: '柯基圈',
      location: '朝阳区望京',
      time: '30 分钟前',
      zone: 'dog',
      content: '【寻宠互助】柴犬豆豆于昨晚 8 点在望京 SOHO 附近走失，戴红色项圈，有酬谢！',
      likes: 18,
      comments: 6,
      liked: false,
      lostType: 'lost',
      image: REAL.pup,
      geoLocation: { name: '望京 SOHO 北门', address: '北京市朝阳区望京街' },
    },
    {
      id: 'p-found1',
      userName: '热心宠友',
      petName: '—',
      avatar: REAL.cat,
      circle: '柯基圈',
      location: '海淀区中关村',
      time: '2 小时前',
      zone: 'dog',
      content: '【招领互助】中关村地铁站附近捡到小型犬，请失主联系认领。',
      likes: 12,
      comments: 4,
      liked: false,
      lostType: 'found',
    },
  ],
};

const MOCK_HELP = [
  {
    id: 'mh1',
    source: 'mock',
    title: '出差三天求上门喂猫',
    preview: '朝阳区望京，每天早晚各一次，猫粮自备，酬劳可谈',
    time: '2 小时前',
    contact: '微信私聊',
    desc: '朝阳区望京，每天早晚各一次，猫粮自备，酬劳可谈',
  },
  {
    id: 'mh2',
    source: 'mock',
    title: '周末帮忙遛狗 2 小时',
    preview: '海淀区中关村，柯基很乖，需有遛狗经验',
    time: '1 天前',
    contact: '138****5678',
    desc: '海淀区中关村，柯基很乖，需有遛狗经验',
  },
];

const MOCK_RESCUE = [
  {
    id: 'mr-adopt1',
    source: 'mock',
    kind: 'adopt',
    tag: '领养',
    title: '狸花小猫求靠谱家庭',
    preview: '三个月大，已驱虫疫苗，性格粘人，希望有养猫经验的家庭领养。',
    time: '1 天前',
    location: '海淀区',
    desc: '三个月大，已驱虫疫苗，性格粘人，希望有养猫经验的家庭领养。',
    contact: '私信联系',
  },
];

const MOCK_EVENTS = [
  {
    id: 'e1',
    source: 'official',
    sourceText: '官方自营',
    tag: '本周六',
    title: '朝阳公园狗狗社交趴',
    cover: REAL.pup,
    fee: '免费',
    place: '朝阳公园南门',
    time: '周六 10:00-12:00',
    seats: '28/40',
    remain: 12,
    require: '须带牵引绳与疫苗本',
    host: '宠头头官方',
    hostId: 'host_e1',
    hostPetName: '官方活动',
    hostAvatar: REAL.avatar,
    desc: '大型犬友好 · 分组互动 · 训犬师在场指导',
  },
  {
    id: 'e2',
    source: 'user',
    sourceText: '用户发起',
    tag: '本周日',
    title: '喵星人咖啡馆见面会',
    cover: REAL.cat,
    fee: '¥39/人',
    place: '三里屯猫咖',
    time: '周日 14:00-16:00',
    seats: '16/22',
    remain: 6,
    require: '须带疫苗本',
    host: '小橘妈',
    hostId: 'host_e2',
    hostPetName: '小橘',
    hostAvatar: REAL.cat,
    desc: '室内温馨局 · 适合慢热猫咪',
  },
  {
    id: 'e3',
    source: 'merchant',
    sourceText: '商家合作',
    tag: '下周五',
    title: '宠物店洗护体验日',
    cover: REAL.svc1,
    fee: '¥68起',
    place: '艾西娜美容中心',
    time: '周五 10:00-18:00',
    seats: '8/15',
    remain: 7,
    require: '需预约',
    host: '艾西娜商家',
    hostId: 'host_e3',
    hostPetName: '商家服务',
    hostAvatar: REAL.svc2,
    desc: '携宠到店洗护 · 赠送拍照服务',
  },
];

const MOCK_MAP_POINTS = [
  { id: 'm1', name: '朝阳公园南门', type: '公园', allowPet: true, distance: '1.2km', address: '北京市朝阳区朝阳公园南路1号', city: '北京', latitude: 39.9334, longitude: 116.4732, rating: 4.8 },
  { id: 'm2', name: 'Paw Coffee', type: '咖啡馆', allowPet: true, distance: '2.0km', address: '北京市朝阳区三里屯路19号', city: '北京', latitude: 39.9367, longitude: 116.4551, rating: 4.6 },
  { id: 'm3', name: '奥林匹克森林公园', type: '公园', allowPet: true, distance: '3.5km', address: '北京市朝阳区科荟路33号', city: '北京', latitude: 40.0178, longitude: 116.3974, rating: 4.7 },
  { id: 'm4', name: '某商场中庭', type: '其他', allowPet: false, distance: '4.1km', address: '北京市朝阳区禁止携宠入内', city: '北京', latitude: 39.9212, longitude: 116.4434, rating: 3.2 },
];

const MOCK_MERCHANTS = [
  { id: 'mer1', name: '阿斯特宠物护理', category: '上门喂养', price: '¥68起', rating: 5, cover: REAL.svc1, tags: ['实名认证', '意外险'] },
  { id: 'mer2', name: '艾西娜美容中心', category: '洗护美容', price: '¥128起', rating: 5, cover: REAL.svc2, tags: ['可预约'] },
  { id: 'mer3', name: '米娅健康诊所', category: '宠物医院', price: '¥199起', rating: 4.9, cover: REAL.pup, tags: ['疫苗驱虫'] },
];

const MOCK_CHATS = [
  { id: 'c1', peerId: 'bd1', peerName: '芒果爸', petName: '芒果', avatar: REAL.pup, lastMessage: '周六公园见？', lastTime: '刚刚', unread: 2 },
  { id: 'c2', peerId: 'bd2', peerName: '布偶姐姐', petName: '糯米', avatar: REAL.cat, lastMessage: '可以先线上聊～', lastTime: '2小时前', unread: 0 },
];

const RISK_TIPS = {
  meet: '线下搭子见面建议在公共场所，查看对方电子宠证，注意人身安全。',
  match: '宠物相亲/借配：平台仅信息展示，不担保交易，风险由用户自行承担。',
  help: '邻里互助：平台仅信息中介，不承担人身财产风险，请谨慎选择。',
  adopt: '领养救助：平台仅信息展示，不参与交易，请线下核实并签署协议。',
};

module.exports = {
  REAL,
  MOCK_PET,
  MOCK_HOME,
  BUDDY_TYPES,
  MOCK_BUDDY,
  MOCK_SOCIAL,
  MOCK_RESCUE,
  MOCK_HELP,
  MOCK_EVENTS,
  MOCK_MAP_POINTS,
  MOCK_MERCHANTS,
  MOCK_CHATS,
  RISK_TIPS,
  MOCK_NEARBY: MOCK_BUDDY,
};
