/**
 * 宠头头 · 宠物搭子交友 Mock（对齐交付文档 MVP）
 */

const BASE = '/assets/mock';

const REAL = {
  avatar: `${BASE}/real_avatar.jpg`,
  tallDog: `${BASE}/real_tall_dog.jpg`,
  cat: `${BASE}/real_cat.jpg`,
  pup: `${BASE}/real_pup.jpg`,
  hero: `${BASE}/real_hero.jpg`,
  svc1: `${BASE}/real_svc1.jpg`,
  svc2: `${BASE}/real_svc2.jpg`,
};

const MOCK_PET = {
  name: '豆豆',
  breed: '柴犬',
  breedName: '柴犬',
  species: 2,
  age: '2岁',
  gender: 1,
  isSterilized: true,
  verified: true,
  personality: '活泼外向',
  socialTags: ['爱遛狗', '友好', '已绝育'],
  avatar: REAL.avatar,
  avatarUrl: REAL.avatar,
  cover: REAL.hero,
};

const MOCK_HOME = {
  city: '北京',
  banners: [
    {
      id: 'map_points_campaign',
      type: 'mapPointsCampaign',
      title: '宠物友好地图 · 标记赠积分',
      subtitle: '积分可兑换礼品',
      tag: '热门活动',
      cover: REAL.hero,
      url: '/pages/friendly-map/friendly-map',
    },
    {
      id: 'b1',
      title: '周末携宠露营季',
      cover: REAL.hero,
      type: 'official',
      url: '/pages/event-detail/event-detail?id=e1',
    },
    {
      id: 'b2',
      title: '宠物友好咖啡馆地图上线',
      cover: REAL.cat,
      type: 'platform',
      url: '/pages/friendly-map/friendly-map',
    },
    {
      id: 'b3',
      title: '同城遛狗搭子招募中',
      cover: REAL.pup,
      type: 'event',
      url: '/pages/buddy/buddy',
    },
  ],
  /** 首页 bento 宫格（参照布丁 Pudding 风格） */
  featureTiles: {
    buddy: {
      id: 'buddy',
      name: '宠友搭子',
      subtitle: '用「陪伴」融化它们的孤独',
      deco: '🐕',
      theme: 'blue',
      layout: 'large',
      path: '/pages/buddy/buddy',
      heroImg: REAL.svc1,
      thumbs: [REAL.avatar, REAL.cat, REAL.pup],
    },
    map: {
      id: 'map',
      name: '友好地图',
      subtitle: '携宠友好点位',
      deco: '🌳',
      theme: 'orange',
      layout: 'wide-half',
      path: '/pages/local/local?tab=map',
      heroImg: `${BASE}/guide_dog.png`,
      cornerImg: `${BASE}/guide_dog.png`,
    },
    rescue: {
      id: 'rescue',
      name: '寻宠 · 领养 · 救助',
      subtitle: '走失寻回 · 爱心领养 · 救助',
      deco: '🐕‍🦺',
      theme: 'warm',
      layout: 'small',
      path: '/pages/pet-rescue/pet-rescue',
      heroImg: `${BASE}/dog.png`,
    },
  },
  grid: [],
};

const HEALING_EVENT_CATEGORY = '疗愈活动';

const EVENT_CATEGORIES = [
  '遛狗社交',
  '撸猫社交',
  '宠物聚会',
  '萌宠摄影',
  '宠物科普',
  '爱心领养',
  '赛事举办',
  HEALING_EVENT_CATEGORY,
  '其他',
];

const NORMAL_BUDDY_TYPES = ['遛狗搭子', '撸猫搭子', '携宠旅行搭子', '露营搭子', '宠物下午茶', '异宠交流'];
const HEALING_BUDDY_TYPES = ['疗愈散步搭子', '情绪陪伴交流', '老年宠照护', '康复遛弯同行'];
const BUDDY_TYPES = [...NORMAL_BUDDY_TYPES, '宠物相亲&借配', ...HEALING_BUDDY_TYPES];

function buddyTypesForZone(zone) {
  if (zone === 'match') return ['宠物相亲&借配'];
  if (zone === 'healing') return HEALING_BUDDY_TYPES;
  return NORMAL_BUDDY_TYPES;
}

const MOCK_BUDDY = [
  {
    id: 'bd1',
    userName: '芒果爸',
    avatar: REAL.pup,
    distance: '0.8km',
    petName: '芒果',
    breed: '金毛',
    age: '3岁',
    verified: true,
    personality: '温柔耐心',
    buddyType: '遛狗搭子',
    tags: ['大型犬', '已绝育'],
    expectTime: '周末上午',
    expectPlace: '朝阳公园',
    expectPlaceAddress: '北京市朝阳区朝阳公园南路1号',
    location: {
      name: '朝阳公园',
      address: '北京市朝阳区朝阳公园南路1号',
      latitude: 39.9334,
      longitude: 116.4732,
    },
    desc: '想找同体型狗狗一起慢跑，芒果性格很好，不扑人。',
    creditTags: ['守约', '宠物温顺'],
    zone: 'normal',
    mediaList: [
      { type: 'image', url: REAL.pup },
      { type: 'image', url: REAL.hero },
      { type: 'video', url: REAL.pup, poster: REAL.pup, duration: 12 },
    ],
    cover: REAL.pup,
    likes: 16,
    comments: 5,
    shares: 2,
  },
  {
    id: 'bd2',
    userName: '布偶姐姐',
    avatar: REAL.cat,
    distance: '1.2km',
    petName: '糯米',
    breed: '布偶猫',
    age: '1岁',
    verified: true,
    personality: '慢热粘人',
    buddyType: '宠物下午茶',
    tags: ['室内猫', '已疫苗'],
    expectTime: '周日下午',
    expectPlace: '三里屯猫咖',
    expectPlaceAddress: '北京市朝阳区三里屯路19号',
    location: {
      name: '三里屯猫咖',
      address: '北京市朝阳区三里屯路19号',
      latitude: 39.9367,
      longitude: 116.4551,
    },
    desc: '希望找慢热猫咪家长，一起适应社交环境。',
    creditTags: ['守约'],
    zone: 'normal',
    mediaList: [
      { type: 'image', url: REAL.cat },
      { type: 'image', url: REAL.avatar },
    ],
    cover: REAL.cat,
    likes: 9,
    comments: 3,
    shares: 1,
  },
  {
    id: 'bd3',
    userName: '柯基小队',
    avatar: REAL.avatar,
    distance: '2.1km',
    petName: '短腿',
    breed: '柯基',
    age: '2岁',
    verified: false,
    personality: '话痨社牛',
    buddyType: '露营搭子',
    tags: ['小型犬', '爱拍照'],
    expectTime: '下月初',
    expectPlace: '怀柔营地',
    expectPlaceAddress: '北京市怀柔区雁栖湖路甲1号',
    location: {
      name: '怀柔营地',
      address: '北京市怀柔区雁栖湖路甲1号',
      latitude: 40.3226,
      longitude: 116.6319,
    },
    desc: '计划携宠露营，找2-3个小型犬家庭同行。',
    creditTags: ['守约', '文明养宠'],
    zone: 'normal',
    mediaList: [
      { type: 'image', url: REAL.hero },
      { type: 'video', url: REAL.tallDog, poster: REAL.tallDog, duration: 18 },
      { type: 'image', url: REAL.pup },
      { type: 'image', url: REAL.avatar },
    ],
    cover: REAL.hero,
  },
  {
    id: 'bd4',
    userName: '柴犬研究社',
    avatar: REAL.avatar,
    distance: '3.0km',
    petName: '小柴',
    breed: '柴犬',
    age: '2岁',
    verified: true,
    personality: '活泼',
    buddyType: '宠物相亲&借配',
    tags: ['已疫苗', '血统证书'],
    expectTime: '可协商',
    expectPlace: '宠物医院见面',
    expectPlaceAddress: '北京市朝阳区望京街10号',
    location: {
      name: '宠物医院见面',
      address: '北京市朝阳区望京街10号',
      latitude: 39.9962,
      longitude: 116.4818,
    },
    desc: '寻找健康同龄柴犬借配，需出示疫苗与体检记录。',
    creditTags: [],
    zone: 'match',
    mediaList: [
      { type: 'image', url: REAL.tallDog },
      { type: 'video', url: REAL.avatar, poster: REAL.avatar, duration: 8 },
    ],
    cover: REAL.tallDog,
  },
  {
    id: 'bd5',
    userName: '暖爪心理',
    avatar: REAL.cat,
    distance: '1.5km',
    petName: '团子',
    breed: '英短',
    age: '4岁',
    verified: true,
    personality: '安静治愈',
    buddyType: '情绪陪伴交流',
    tags: ['慢节奏', '室内友好'],
    expectTime: '工作日晚间',
    expectPlace: '宠物友好咖啡馆',
    expectPlaceAddress: '北京市海淀区中关村大街27号',
    location: {
      name: '宠物友好咖啡馆',
      address: '北京市海淀区中关村大街27号',
      latitude: 39.9834,
      longitude: 116.3155,
    },
    desc: '团子经历过分离焦虑，想找同样需要情绪支持的家长，一起慢走、轻声交流，不强迫社交。',
    creditTags: ['守约', '尊重边界'],
    zone: 'healing',
    mediaList: [{ type: 'image', url: REAL.cat }],
    cover: REAL.cat,
    likes: 12,
    comments: 4,
    shares: 0,
  },
  {
    id: 'bd6',
    userName: '康复日记',
    avatar: REAL.pup,
    distance: '2.8km',
    petName: '乐乐',
    breed: '田园犬',
    age: '8岁',
    verified: true,
    personality: '稳重',
    buddyType: '康复遛弯同行',
    tags: ['术后恢复', '短距慢行'],
    expectTime: '每日清晨',
    expectPlace: '社区绿道',
    expectPlaceAddress: '北京市丰台区南四环西路188号',
    location: {
      name: '社区绿道',
      address: '北京市丰台区南四环西路188号',
      latitude: 39.8585,
      longitude: 116.2867,
    },
    desc: '乐乐髋关节术后康复中，寻找同样老年/康复期毛孩家庭，结伴短距散步，互相打气。',
    creditTags: ['守约', '文明养宠'],
    zone: 'healing',
    mediaList: [
      { type: 'image', url: REAL.pup },
      { type: 'image', url: REAL.hero },
    ],
    cover: REAL.pup,
    likes: 7,
    comments: 2,
    shares: 1,
  },
];

const MOCK_SOCIAL = {
  innerTabs: [
    { id: 'all', name: '社区动态' },
    { id: 'featured', name: '精选社区' },
    { id: 'circle', name: '宠物圈子' },
    { id: 'topic', name: '话题' },
    { id: 'qa', name: '问答求助' },
  ],
  circles: [
    { id: 'c1', name: '柯基圈', icon: '🐕', members: 1280, cover: REAL.tallDog },
    { id: 'c2', name: '布偶猫圈', icon: '🐱', members: 960, cover: REAL.cat },
    { id: 'c3', name: '异宠圈', icon: '🦔', members: 420, cover: REAL.pup },
    { id: 'c4', name: '携宠旅行圈', icon: '🐕‍🦺', members: 680, cover: REAL.hero },
  ],
  topics: [
    { id: 't1', name: '#携宠露营', posts: 128, hot: true },
    { id: 't2', name: '#猫咪喂养', posts: 86 },
    { id: 't3', name: '#避雷宠物店', posts: 204, hot: true },
    { id: 't4', name: '#第一次见朋友', posts: 67 },
  ],
  qaList: [
    { id: 'q1', userName: '新手铲屎官', title: '两个月幼犬可以社交吗？', answers: 8, best: true },
    { id: 'q2', userName: '猫奴小白', title: '猫咪出门应激怎么办？', answers: 12, best: false },
  ],
  posts: [
    {
      id: 'p1',
      userName: '小橘妈',
      petName: '橘子',
      avatar: REAL.cat,
      circle: '布偶猫圈',
      location: '朝阳区',
      time: '10 分钟前',
      zone: 'cat',
      topic: '#携宠露营',
      content: '周末有没有朝阳附近一起遛猫社交的？橘子最近交友欲超强 🐾',
      likes: 24,
      comments: 8,
      liked: false,
      shares: 3,
      image: REAL.cat,
    },
    {
      id: 'p2',
      userName: '阿柴爸爸',
      petName: '团团',
      avatar: REAL.avatar,
      circle: '柯基圈',
      location: '海淀区',
      time: '1 小时前',
      zone: 'dog',
      topic: '#第一次见朋友',
      content: '团团第一次见朋友，尾巴摇成螺旋桨了～',
      likes: 56,
      comments: 13,
      liked: true,
      image: REAL.tallDog,
      essence: true,
      shares: 12,
    },
    {
      id: 'p-lost1',
      userName: '豆豆爸',
      petName: '豆豆',
      avatar: REAL.avatar,
      circle: '柯基圈',
      location: '朝阳区望京',
      time: '30 分钟前',
      zone: 'dog',
      content: '【寻宠互助】柴犬豆豆于昨晚 8 点在望京 SOHO 附近走失，戴红色项圈，有酬谢！',
      likes: 18,
      comments: 6,
      liked: false,
      lostType: 'lost',
      image: REAL.pup,
      geoLocation: {
        name: '望京 SOHO 北门',
        address: '北京市朝阳区望京街',
        latitude: 39.9968,
        longitude: 116.4808,
      },
    },
    {
      id: 'p-found1',
      userName: '热心宠友',
      petName: '—',
      avatar: REAL.cat,
      circle: '柯基圈',
      location: '海淀区中关村',
      time: '2 小时前',
      zone: 'dog',
      content: '【招领互助】中关村地铁站附近捡到小型犬，请失主联系认领。',
      likes: 12,
      comments: 4,
      liked: false,
      lostType: 'found',
    },
    {
      id: 'p-other1',
      userName: '仓鼠家长',
      petName: '瓜子',
      avatar: REAL.pup,
      location: '丰台区',
      time: '3 小时前',
      zone: 'other',
      topic: '#异宠日常',
      content: '给仓鼠换了新垫料，第一次见它这么兴奋地跑轮子～',
      likes: 31,
      comments: 9,
      liked: false,
      image: REAL.pup,
    },
    {
      id: 'p-act1',
      userName: '活动局主',
      petName: '全员',
      avatar: REAL.hero,
      location: '朝阳公园',
      time: '5 小时前',
      zone: 'activity',
      topic: '#周末遛狗局',
      content: '本周六上午朝阳公园南门集合，中型犬友好，自带牵引和捡屎袋～',
      likes: 42,
      comments: 15,
      liked: false,
      image: REAL.hero,
    },
    {
      id: 'p-photo1',
      userName: '镜头下的毛孩',
      petName: '米洛',
      avatar: REAL.cat,
      location: '三里屯',
      time: '昨天',
      zone: 'photo',
      topic: '#宠物摄影',
      content: '逆光拍猫咪轮廓，手机就行！分享三点构图小技巧…',
      likes: 88,
      comments: 22,
      liked: true,
      image: REAL.cat,
      shares: 6,
    },
    {
      id: 'p-social1',
      userName: '社牛柯基',
      petName: '豆包',
      avatar: REAL.avatar,
      location: '望京',
      time: '昨天',
      zone: 'social',
      content: '想给豆包找固定遛狗搭子，性格友好不扑人，周末可约～',
      likes: 27,
      comments: 11,
      liked: false,
      image: REAL.tallDog,
    },
    {
      id: 'p-expose1',
      userName: '理性铲屎官',
      petName: '—',
      avatar: REAL.avatar,
      location: '同城',
      time: '2 天前',
      zone: 'expose',
      topic: '#避雷宠物店',
      content: '某店洗护强行推销套餐，猫咪应激还甩锅主人，大家选店前多看评价。',
      likes: 120,
      comments: 45,
      liked: false,
    },
  ],
};

const MOCK_HELP = [
  {
    id: 'mh1',
    source: 'mock',
    title: '出差三天求上门喂猫',
    preview: '朝阳区望京，每天早晚各一次，猫粮自备，酬劳可谈',
    time: '2 小时前',
    contact: '微信私聊',
    desc: '朝阳区望京，每天早晚各一次，猫粮自备，酬劳可谈',
  },
  {
    id: 'mh2',
    source: 'mock',
    title: '周末帮忙遛狗 2 小时',
    preview: '海淀区中关村，柯基很乖，需有遛狗经验',
    time: '1 天前',
    contact: '138****5678',
    desc: '海淀区中关村，柯基很乖，需有遛狗经验',
  },
];

const MOCK_RESCUE = [
  {
    id: 'mr-adopt1',
    source: 'mock',
    kind: 'adopt',
    tag: '领养',
    title: '狸花小猫求靠谱家庭',
    preview: '三个月大，已驱虫疫苗，性格粘人，希望有养猫经验的家庭领养。',
    time: '1 天前',
    location: '海淀区',
    desc: '三个月大，已驱虫疫苗，性格粘人，希望有养猫经验的家庭领养。',
    contact: '私信联系',
  },
];

const MOCK_EVENTS = [
  {
    id: 'e1',
    source: 'official',
    sourceText: '官方自营',
    tag: '本周六',
    title: '朝阳公园狗狗社交趴',
    cover: REAL.pup,
    fee: '免费报名',
    place: '朝阳公园南门',
    placeAddress: '北京市朝阳区朝阳公园南路1号',
    location: {
      name: '朝阳公园南门',
      address: '北京市朝阳区朝阳公园南路1号',
      latitude: 39.9334,
      longitude: 116.4732,
    },
    time: '周六 10:00-12:00',
    seats: '28/40',
    remain: 12,
    require: '须带牵引绳与疫苗本',
    host: '宠头头官方',
    hostId: 'host_e1',
    hostPetName: '官方活动',
    hostAvatar: REAL.avatar,
    desc: '大型犬友好 · 分组互动 · 训犬师在场指导',
    category: '遛狗社交',
  },
  {
    id: 'e2',
    source: 'user',
    sourceText: '用户发起',
    tag: '本周日',
    title: '喵星人咖啡馆见面会',
    cover: REAL.cat,
    fee: '免费报名',
    place: '三里屯猫咖',
    placeAddress: '北京市朝阳区三里屯路19号',
    location: {
      name: '三里屯猫咖',
      address: '北京市朝阳区三里屯路19号',
      latitude: 39.9367,
      longitude: 116.4551,
    },
    time: '周日 14:00-16:00',
    seats: '16/22',
    remain: 6,
    require: '须带疫苗本',
    host: '小橘妈',
    hostId: 'host_e2',
    hostPetName: '小橘',
    hostAvatar: REAL.cat,
    desc: '室内温馨局 · 适合慢热猫咪',
    detailContent:
      '本场为室内猫咪社交小局，猫咖提供独立包间与猫树活动区。\n\n'
      + '流程：签到 → 熟悉环境 → 自由互动 → 合影留念。\n\n'
      + '温馨提示：请自备疫苗本；猫咪紧张可先在外间适应 10 分钟再入场。',
    detailMediaList: [
      { type: 'image', url: REAL.svc1 },
      { type: 'image', url: REAL.pup },
      { type: 'image', url: REAL.tallDog },
    ],
    detailImages: [REAL.svc1, REAL.pup, REAL.tallDog],
    mediaList: [
      { type: 'image', url: REAL.cat },
      { type: 'image', url: REAL.svc1 },
      { type: 'image', url: REAL.pup },
      { type: 'image', url: REAL.tallDog },
      { type: 'image', url: REAL.hero },
      { type: 'image', url: REAL.svc2 },
    ],
    images: [REAL.cat, REAL.svc1, REAL.pup, REAL.tallDog, REAL.hero, REAL.svc2],
    category: '撸猫社交',
  },
  {
    id: 'e3',
    source: 'merchant',
    sourceText: '商家合作',
    tag: '下周五',
    title: '宠物店洗护体验日',
    cover: REAL.svc1,
    fee: '免费报名',
    place: '艾西娜美容中心',
    placeAddress: '北京市朝阳区工体北路4号',
    location: {
      name: '艾西娜美容中心',
      address: '北京市朝阳区工体北路4号',
      latitude: 39.9364,
      longitude: 116.4523,
    },
    time: '周五 10:00-18:00',
    seats: '8/15',
    remain: 7,
    require: '需预约',
    host: '艾西娜商家',
    hostId: 'host_e3',
    hostPetName: '商家服务',
    hostAvatar: REAL.svc2,
    desc: '携宠到店洗护 · 赠送拍照服务',
    category: '萌宠摄影',
  },
  {
    id: 'e4',
    source: 'official',
    sourceText: '官方自营',
    tag: '本周末',
    title: '毛孩情绪疗愈慢走局',
    cover: REAL.cat,
    fee: '免费报名',
    place: '奥林匹克森林公园',
    placeAddress: '北京市朝阳区科荟路33号',
    location: {
      name: '奥林匹克森林公园',
      address: '北京市朝阳区科荟路33号',
      latitude: 40.0179,
      longitude: 116.3965,
    },
    time: '周六 09:00-11:00',
    seats: '12/20',
    remain: 8,
    require: '慢节奏、尊重边界；紧张毛孩可全程牵绳',
    host: '暖爪心理 · 宠头头合作',
    hostId: 'host_e4',
    hostPetName: '团子',
    hostAvatar: REAL.cat,
    desc: '专业引导员带队 · 分组慢走 · 情绪陪伴交流（非医疗）',
    category: HEALING_EVENT_CATEGORY,
    detailContent:
      '适合分离焦虑、慢热或康复期毛孩家庭。\n\n'
      + '流程：签到破冰 → 慢走 40 分钟 → 围坐分享 → 自由交流。\n\n'
      + '说明：本场为情绪支持与陪伴活动，不能替代兽医或专业行为治疗。',
    detailMediaList: [{ type: 'image', url: REAL.cat }, { type: 'image', url: REAL.hero }],
  },
];

const MOCK_CLUBS = [
  {
    id: 'club_park',
    name: '朝阳公园遛狗社',
    city: '北京',
    intro: '每周末朝阳公园集合，大型犬友好，主人社交局',
    cover: `${BASE}/real_hero.jpg`,
    members: 128,
    owner: '柯基爸爸',
  },
  {
    id: 'club_cat',
    name: '猫咪下午茶俱乐部',
    city: '北京',
    intro: '室内猫友聚会，布偶/英短/橘猫为主，每周主题活动',
    cover: `${BASE}/real_cat.jpg`,
    members: 86,
    owner: '鱼干小姐',
  },
  {
    id: 'club_hike',
    name: '周末携宠徒步团',
    city: '北京',
    intro: '近郊轻徒步路线，中大型犬体能局，月均 2 次',
    cover: `${BASE}/real_tall_dog.jpg`,
    members: 203,
    owner: '边牧教练',
  },
];

const MOCK_MAP_POINTS = [
  // 宠物友好公园
  { id: 'm1', name: '朝阳公园南门', type: '宠物友好公园', allowPet: true, distance: '1.2km', address: '北京市朝阳区朝阳公园南路1号', city: '北京', latitude: 39.9334, longitude: 116.4732, rating: 4.8 },
  { id: 'm3', name: '奥林匹克森林公园', type: '宠物友好公园', allowPet: true, distance: '3.5km', address: '北京市朝阳区科荟路33号', city: '北京', latitude: 40.0178, longitude: 116.3974, rating: 4.7 },
  { id: 'm5', name: '将府公园（携宠区）', type: '宠物友好公园', allowPet: true, distance: '5.2km', address: '北京市朝阳区将台乡东八间房村', city: '北京', latitude: 39.9788, longitude: 116.4485, rating: 4.5 },
  // 宠物友好酒店
  { id: 'm6', name: '汪汪假日酒店·望京店', type: '宠物友好酒店', allowPet: true, distance: '6.8km', address: '北京市朝阳区望京街10号', city: '北京', latitude: 39.9962, longitude: 116.4818, rating: 4.6 },
  { id: 'm7', name: '喵界精选酒店·三里屯', type: '宠物友好酒店', allowPet: true, distance: '2.3km', address: '北京市朝阳区工体北路4号', city: '北京', latitude: 39.9364, longitude: 116.4523, rating: 4.9 },
  // 宠物友好商场
  { id: 'm8', name: '爪爪广场·通州店', type: '宠物友好商场', allowPet: true, distance: '12.1km', address: '北京市通州区九棵树东路', city: '北京', latitude: 39.8853, longitude: 116.6564, rating: 4.4 },
  { id: 'm9', name: '萌宠次元购物中心', type: '宠物友好商场', allowPet: true, distance: '7.4km', address: '北京市丰台区万丰路68号', city: '北京', latitude: 39.8598, longitude: 116.2874, rating: 4.3 },
  // 宠物友好餐厅
  { id: 'm10', name: '汪咖餐厅·五道口', type: '宠物友好餐厅', allowPet: true, distance: '9.6km', address: '北京市海淀区成府路28号', city: '北京', latitude: 39.9926, longitude: 116.3378, rating: 4.5 },
  { id: 'm11', name: '猫爪火锅·国贸店', type: '宠物友好餐厅', allowPet: true, distance: '4.9km', address: '北京市朝阳区建国门外大街1号', city: '北京', latitude: 39.9087, longitude: 116.4564, rating: 4.7 },
  // 宠物友好景区
  { id: 'm12', name: '雁栖湖萌宠景区', type: '宠物友好景区', allowPet: true, distance: '38.2km', address: '北京市怀柔区雁栖湖路甲1号', city: '北京', latitude: 40.3226, longitude: 116.6319, rating: 4.8 },
  { id: 'm13', name: '古韵园林·携宠步道', type: '宠物友好景区', allowPet: true, distance: '18.5km', address: '北京市海淀区青龙桥街道', city: '北京', latitude: 40.0068, longitude: 116.2729, rating: 4.6 },
  // 宠物友好露营地
  { id: 'm14', name: '星空宠物露营地', type: '宠物友好露营地', allowPet: true, distance: '45.0km', address: '北京市平谷区黄松峪乡', city: '北京', latitude: 40.1815, longitude: 117.1815, rating: 4.9 },
  { id: 'm15', name: '湖畔萌宠露营园', type: '宠物友好露营地', allowPet: true, distance: '28.3km', address: '北京市房山区青龙湖镇', city: '北京', latitude: 39.7426, longitude: 116.0861, rating: 4.7 },
  // 其他
  { id: 'm2', name: 'Paw Coffee', type: '宠物友好餐厅', allowPet: true, distance: '2.0km', address: '北京市朝阳区三里屯路19号', city: '北京', latitude: 39.9367, longitude: 116.4551, rating: 4.6 },
  { id: 'm4', name: '某商场中庭', type: '宠物不友好', allowPet: false, distance: '4.1km', address: '北京市朝阳区禁止携宠入内', city: '北京', latitude: 39.9212, longitude: 116.4434, rating: 3.2 },
  { id: 'm16', name: '静音自习咖啡馆', type: '宠物不友好', allowPet: false, distance: '5.6km', address: '北京市海淀区中关村大街27号', city: '北京', latitude: 39.9832, longitude: 116.3164, rating: 4.2 },
  // 危险 / 毒点
  { id: 'm17', name: '绿化带灭鼠饵站', type: '毒点', danger: true, dangerDesc: '投放灭鼠药，请勿让宠物靠近嗅闻', allowPet: false, distance: '1.8km', address: '北京市朝阳区东三环辅路绿化带', city: '北京', latitude: 39.9286, longitude: 116.4612, rating: 0 },
  { id: 'm18', name: '夹竹桃有毒植物区', type: '毒点', danger: true, dangerDesc: '全株有毒，误食叶片可致中毒', allowPet: false, distance: '3.2km', address: '北京市丰台区世界公园北侧', city: '北京', latitude: 39.8062, longitude: 116.2986, rating: 0 },
  { id: 'm19', name: '车流密集无斑马线路段', type: '危险', danger: true, dangerDesc: '大货车多、无视险横穿，请牵好宠物', allowPet: false, distance: '2.7km', address: '北京市朝阳区双桥东路', city: '北京', latitude: 39.9108, longitude: 116.5489, rating: 0 },
];

const MOCK_MERCHANTS = [
  { id: 'mer1', name: '阿斯特宠物护理', category: '上门喂养', price: '¥68起', rating: 5, cover: REAL.svc1, tags: ['实名认证', '意外险'] },
  { id: 'mer2', name: '艾西娜美容中心', category: '洗护美容', price: '¥128起', rating: 5, cover: REAL.svc2, tags: ['可预约'] },
  { id: 'mer3', name: '米娅健康诊所', category: '宠物医院', price: '¥199起', rating: 4.9, cover: REAL.pup, tags: ['疫苗驱虫'] },
];

const MOCK_CHATS = [
  { id: 'c1', peerId: 'bd1', peerName: '芒果爸', petName: '芒果', avatar: REAL.pup, lastMessage: '周六公园见？', lastTime: '刚刚', unread: 2 },
  { id: 'c2', peerId: 'bd2', peerName: '布偶姐姐', petName: '糯米', avatar: REAL.cat, lastMessage: '可以先线上聊～', lastTime: '2小时前', unread: 0 },
];

const RISK_TIPS = {
  event: '线下活动请注意人身与宠物安全，结伴同行、选择公共场所；平台仅提供信息展示与报名撮合，不参与线下组织，不对活动中的人身、财产损害承担责任。',
  meet: '线下搭子见面建议在公共场所，查看对方电子宠证，注意人身安全。',
  match: '宠物相亲/借配：平台仅信息展示，不担保交易，风险由用户自行承担。',
  healing:
    '疗愈搭子侧重情绪支持与陪伴交流，不能替代兽医或专业行为治疗；宠物或主人出现紧急健康/心理危机，请及时就医或求助专业机构。',
  healingEvent:
    '疗愈活动侧重情绪支持与陪伴体验，不能替代兽医或专业行为治疗；如有紧急健康/心理危机，请及时就医或求助专业机构。',
  help: '邻里互助：平台仅信息中介，不承担人身财产风险，请谨慎选择。',
  adopt: '领养救助：平台仅信息展示，不参与交易，请线下核实并签署协议。',
};

module.exports = {
  REAL,
  MOCK_PET,
  MOCK_HOME,
  HEALING_EVENT_CATEGORY,
  EVENT_CATEGORIES,
  BUDDY_TYPES,
  NORMAL_BUDDY_TYPES,
  HEALING_BUDDY_TYPES,
  buddyTypesForZone,
  MOCK_BUDDY,
  MOCK_SOCIAL,
  MOCK_RESCUE,
  MOCK_HELP,
  MOCK_EVENTS,
  MOCK_MAP_POINTS,
  MOCK_MERCHANTS,
  MOCK_CLUBS,
  MOCK_CHATS,
  RISK_TIPS,
  MOCK_NEARBY: MOCK_BUDDY,
};
