/**
 * 宠头头 · 宠物交友 Mock 数据
 */

const BASE = '/assets/mock';

const REAL = {
  avatar: `${BASE}/real_avatar.jpg`,
  tallDog: `${BASE}/real_tall_dog.jpg`,
  cat: `${BASE}/real_cat.jpg`,
  pup: `${BASE}/real_pup.jpg`,
  hero: `${BASE}/real_hero.jpg`,
  svc1: `${BASE}/real_svc1.jpg`,
  svc2: `${BASE}/real_svc2.jpg`,
};

const MOCK_PET = {
  name: '豆豆',
  breed: '柴犬',
  species: 2,
  age: '2岁',
  days: 420,
  personality: '活泼外向',
  socialTags: ['爱遛狗', '友好', '已绝育'],
  avatar: REAL.avatar,
  cover: REAL.hero,
};

const MOCK_SOCIAL = {
  actions: [
    { id: 'post', name: '发动态', icon: '✎', desc: '分享日常' },
    { id: 'event', name: '找活动', icon: '🎉', desc: '同城约局' },
    { id: 'nearby', name: '附近宠友', icon: '📍', desc: '发现伙伴' },
    { id: 'topic', name: '话题', icon: '#', desc: '热门讨论' },
  ],
  filters: [
    { id: 'all', name: '推荐' },
    { id: 'dog', name: '狗狗' },
    { id: 'cat', name: '猫咪' },
    { id: 'other', name: '异宠' },
    { id: 'event', name: '约局' },
  ],
  topics: [
    { id: 't1', name: '#周末遛狗局', posts: 128, hot: true },
    { id: 't2', name: '#社恐猫咪适应', posts: 86 },
    { id: 't3', name: '#第一次见朋友', posts: 204, hot: true },
    { id: 't4', name: '#异宠交流', posts: 45 },
    { id: 't5', name: '#公园社交Tips', posts: 67 },
  ],
  events: [
    {
      id: 'e1',
      tag: '本周六',
      title: '朝阳公园狗狗社交趴',
      desc: '大型犬友好 · 分组互动 · 专业训犬师在场',
      cover: REAL.pup,
      zone: 'dog',
      fee: '免费',
      place: '朝阳公园南门',
      time: '周六 10:00-12:00',
      seats: '28/40',
      require: '须带牵引绳与疫苗本',
      host: '阿柴爸爸',
      hostAvatar: REAL.avatar,
    },
    {
      id: 'e2',
      tag: '本周日',
      title: '喵星人咖啡馆见面会',
      desc: '室内温馨局 · 适合慢热猫咪 · 提供猫包寄存',
      cover: REAL.cat,
      zone: 'cat',
      fee: '¥39/人',
      place: '三里屯 · 猫咖',
      time: '周日 14:00-16:00',
      seats: '16/22',
      require: '须带疫苗本',
      host: '小橘妈',
      hostAvatar: REAL.cat,
    },
    {
      id: 'e3',
      tag: '下周五',
      title: '滨江夜遛小型犬专场',
      desc: '5kg 以下小型犬 · 夜风凉爽 · 结束后合影',
      cover: REAL.svc2,
      zone: 'dog',
      fee: '免费',
      place: '滨江步道 B 入口',
      time: '周五 19:30-21:00',
      seats: '12/20',
      require: '须佩戴胸背',
      host: '奶盖屋',
      hostAvatar: REAL.svc2,
    },
  ],
  posts: [
    {
      id: 'p1',
      userName: '小橘妈',
      petName: '橘子',
      avatar: REAL.cat,
      time: '10 分钟前',
      zone: 'cat',
      topic: '#周末遛狗局',
      content: '周末有没有朝阳附近一起遛猫社交的？橘子最近交友欲超强，想找同龄小伙伴 🐾',
      likes: 24,
      comments: 8,
      liked: false,
      essence: false,
      shares: 3,
    },
    {
      id: 'p2',
      userName: '阿柴爸爸',
      petName: '团团',
      avatar: REAL.avatar,
      time: '1 小时前',
      zone: 'dog',
      topic: '#第一次见朋友',
      content: '分享团团第一次见朋友的照片，尾巴摇成螺旋桨了～有没有同款社牛柴犬？',
      likes: 56,
      comments: 13,
      liked: true,
      image: REAL.tallDog,
      essence: true,
      shares: 12,
    },
    {
      id: 'p3',
      userName: '奶盖屋',
      petName: '奶盖',
      avatar: REAL.svc2,
      time: '昨天',
      zone: 'cat',
      topic: '#社恐猫咪适应',
      content: '求推荐温和的宠物社交场，家里宝宝有点社恐，想慢慢适应，有同样经历的朋友吗？',
      likes: 18,
      comments: 21,
      liked: false,
      essence: false,
      shares: 5,
    },
    {
      id: 'p4',
      userName: '异宠研究所',
      petName: '小刺',
      avatar: REAL.pup,
      time: '2 天前',
      zone: 'other',
      topic: '#异宠交流',
      content: '有没有养刺猬的朋友？想交流换笼和温湿度经验，也可以线下小聚～',
      likes: 9,
      comments: 6,
      liked: false,
      essence: false,
      shares: 1,
    },
  ],
  invite: {
    rewardTitle: '邀请宠友一起玩',
    rewardDesc: '分享小程序，好友加入后双方解锁「附近宠友」优先推荐',
    shareTitle: '来宠头头，和同城毛孩子交朋友～',
  },
};

const MOCK_NEARBY = [
  {
    id: 'f1',
    userName: '芒果爸',
    petName: '芒果',
    avatar: REAL.pup,
    cover: REAL.tallDog,
    breed: '金毛',
    species: 2,
    distance: '0.8km',
    personality: '温柔耐心',
    tags: ['大型犬', '已绝育', '爱游泳'],
    wantMeet: '周末公园局',
    online: true,
  },
  {
    id: 'f2',
    userName: '布偶姐姐',
    petName: '糯米',
    avatar: REAL.cat,
    cover: REAL.cat,
    breed: '布偶猫',
    species: 1,
    distance: '1.2km',
    personality: '慢热粘人',
    tags: ['室内猫', '已疫苗', '可上门'],
    wantMeet: '猫友咖啡局',
    online: false,
  },
  {
    id: 'f3',
    userName: '柯基小队',
    petName: '短腿',
    avatar: REAL.avatar,
    cover: REAL.hero,
    breed: '柯基',
    species: 2,
    distance: '2.1km',
    personality: '话痨社牛',
    tags: ['小型犬', '爱拍照', '友好'],
    wantMeet: '夜遛小分队',
    online: true,
  },
  {
    id: 'f4',
    userName: '龙猫小屋',
    petName: '灰灰',
    avatar: REAL.svc1,
    cover: REAL.svc1,
    breed: '龙猫',
    species: 3,
    distance: '3.5km',
    personality: '安静观察型',
    tags: ['异宠', '新手友好'],
    wantMeet: '异宠小聚',
    online: false,
  },
];

const MOCK_CHATS = [
  {
    id: 'c1',
    peerId: 'f1',
    peerName: '芒果爸',
    petName: '芒果',
    avatar: REAL.pup,
    lastMessage: '周六公园见？我可以带飞盘～',
    lastTime: '刚刚',
    unread: 2,
  },
  {
    id: 'c2',
    peerId: 'f2',
    peerName: '布偶姐姐',
    petName: '糯米',
    avatar: REAL.cat,
    lastMessage: '糯米比较慢热，我们可以先线上聊',
    lastTime: '2小时前',
    unread: 0,
  },
];

module.exports = {
  REAL,
  MOCK_PET,
  MOCK_SOCIAL,
  MOCK_NEARBY,
  MOCK_CHATS,
};
